### ISSUE TITLE
Interested in a PR for latest HaxeUI?

### ISSUE THREAD

**Issue by ianharrigan** [TomByrne/StarlingTextDisplay#1]
Hi!

So I was looking at the repo and saw that the demo is haxeui :)

I realised a few things were "off" and then looking at the source i realised that its the haxelib version of haxeui which is painfully out of date. So i downloaded it and thought i might try and give it a little upgrade to the lastest master version of haxeui. So, i was wondering if you would be interested in a PR? It does mean you'd have to use latest git version of haxeui-core and haxeui-html5 to compile it though. I can attach the source here first if you like just to see if you can compile it. (its not actually finished, just thought i would ask the question!)

Regardless if you want the PR or not, it was an incredibly useful test app, as the sliders (even in the master branch) were all wrong and simply didnt work correctly... ... at all! Thats all fixed now... ... so thanks for that!

Cheers,
Ian

**Comment by TomByrne** [comment]
I'm definitely open to PRs.
I would prefer to use a haxelib version, just because it's a little easier for other devs to get going and it's a little cleaner.
Is there any reason you don't want to publish a new version?

**Comment by ianharrigan** [comment]
well, its mainly because im still cleaning up a few little things. I can still make the PR and you can just accept it as and when, ill also post a zip of the "new" source here once im done. The slider issues is a perfect example of why i _dont_ want to publish to haxelib just yet. Though, i guess i probably need to sooner rather than later (think ive been saying that for a year now :/ )

**Comment by TomByrne** [comment]
yeah take the plunge, fix it in post.

**Comment by ianharrigan** [comment]
Ok, heres my changes for the demo: 

[demo.zip](https://github.com/TomByrne/StarlingTextDisplay/files/3717545/demo.zip)

Let me know if you want me to make a PR out of it... You'll need git haxeui-core and haxeui-openfl if you want to test it, ill look to putting 1.0.0 of the libs in haxelib asap... probably this weekend! 

As i mentioned, whether you use the new version or not is totally up to you of course, but thanks to your (totally reasonable) usage of sliders they have been properly fixed now and work as they should, so thanks again for that! 

Also, for the app, ive made moved it all about a little, and made most things custom components... I feel like they are clearer and more modular... plus, no more "findComponent" ugliness :)

Let me know what you think, and if you want me to make a PR.

Cheers,
Ian

**Comment by ianharrigan** [comment]
FYI: haxelibs are all updated now to latest version (1.0.0)

**Comment by TomByrne** [comment]
Thanks Ian,
I've updated that.

**Comment by ianharrigan** [comment]
Is it alright if i link to the demo on twitter?

**Comment by TomByrne** [comment]
Of course

**Comment by ianharrigan** [comment]
OK, nice once... thanks. Ill wait till you've updated the live demo though - unless you already have an its a cache issue?

Cheers,
Ian

**Comment by TomByrne** [comment]
Yeah sorry, updated now.

**Comment by ianharrigan** [comment]
By-the-by... I really like your model stuff... am thinking i might try and incorporate _something_ like that into haxeui... optional ofc but its a nice system

**Comment by TomByrne** [comment]
There are some similar implementations in [notifier](https://lib.haxe.org/p/notifier) and [tink_state](https://lib.haxe.org/p/tink_state).
If I were you though, implementing it in haxeui, I'd come up with a very bare-bones typedef that ui elements accept, so that any of these libraries could be adapted to populate haxeui components.
